CREATE TABLE IF NOT EXISTS FOLDER(
    CHAT_ID         INT  NOT NULL,
    FOLDER_NM       TEXT NOT NULL,
    PARENT_FLDR_ID  INT
);

CREATE TABLE IF NOT EXISTS FILE(
    CHAT_ID         INT  NOT NULL,
    MESSAGE_ID      INT  NOT NULL,
    FILE_NM         TEXT NOT NULL,
    FOLDER_ID       INT
);