CREATE OR REPLACE TABLE FOLDER(
	FOLDER_ID 		INT 				NOT NULL	AUTO_INCREMENT,
	CHAT_ID			INT				NOT NULL,
	FOLDER_NM		VARCHAR(100)	NOT NULL,
	PARENT_FLDR_ID	INT				NULL,
	PRIMARY KEY (FOLDER_ID)
);

CREATE OR REPLACE TABLE FILE(
	FILE_ID			INT				NOT NULL AUTO_INCREMENT,
	CHAT_ID			INT				NOT NULL,
	MESSAGE_ID		INT				NOT NULL,
	FILE_NM			VARCHAR(100)	NOT NULL,
	FOLDER_ID		INT				NULL,
	PRIMARY KEY (FILE_ID)
);